# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Community' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '4.0.1'
  pod 'Masonry', '1.0.2'
  pod 'YYModel', '1.0.4'
  pod 'Toast'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MBProgressHUD', '~> 1.0.0'

  target 'CommunityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommunityUITests' do
    # Pods for testing
  end

end
